version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: safesister
      POSTGRES_USER: apiuser
      POSTGRES_PASSWORD: 12345
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/  # Monta la carpeta donde está el script SQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apiuser"]  # Usar el usuario correcto
      interval: 30s
      timeout: 10s
      retries: 5
    env_file: 
      - ./api/.env  # Ruta actualizada para el archivo .env

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${user}
      DB_PASSWORD: ${password}
      DB_NAME: ${database}
    env_file: 
      - ./api/.env  # Ruta actualizada para el archivo .env
    volumes:
      - ./api:/app

volumes:
  db_data:
